### ISSUE TITLE
Would it be possible to do the fishingrod like at GoMint ?

### ISSUE THREAD

**Issue by LucGamesYT** [GameModsBR/PowerNukkit#104]
Would it be possible to do the fishingrod like at GoMint ? (What you can hit the players like in the Java version)

**Comment by joserobjr** [comment]
I just tested on vanilla and it actually attacks the player like the old java versions. I couldn't test on Nukkit yet but if it is behaving differently then yes, that needs to be changed

**Comment by LucGamesYT** [comment]
Okay thanks! ^^

**Comment by joserobjr** [comment]
I'm closing this issue because it was already answered and is being worked at #116. If you have more questions, suggestions or found an other issue, feel free to open an new issue or reopen this one.
