### ISSUE TITLE
Incorrect piston behaviour when receiving power from repeater

### ISSUE THREAD

**Issue by joserobjr** [GameModsBR/PowerNukkit#119]
As described at: https://github.com/NukkitX/Nukkit/pull/914#issuecomment-573776797
Follow up from #118, #12 

### Expected Behavior
Powering piston with repeater shouldn't trigger blocks, like other pistons behind it
![image](https://user-images.githubusercontent.com/3679022/73138948-04773b80-4047-11ea-8a12-945cdc41983a.png)

### Actual Behavior
The piston transmits the power and doesn't extend
![image](https://user-images.githubusercontent.com/3679022/73138584-063f0000-4043-11ea-8b3f-a1cd59683403.png)

**Comment by Gabriel8579** [comment]
https://youtu.be/9Ilt6dEMKpk

I think in this case is a repeater issue
