### ISSUE TITLE
Wrong redstone signal from levers

### ISSUE THREAD

**Issue by joserobjr** [GameModsBR/PowerNukkit#12]
If we place a redstone wire above a stone block and attach the lever to the side of the block and then trigger it, the redstone wire will not receive power

**Comment by Gabriel8579** [comment]
Same issue when redstone wire is on the block or near the block sides (except when the block side is opposite of the lever)

![image](https://user-images.githubusercontent.com/31969146/73128406-b7935680-3fad-11ea-832a-9f6b1cf06f1b.png)

![image](https://user-images.githubusercontent.com/31969146/73128409-c5e17280-3fad-11ea-96b2-0f4a4f3f61d2.png)
