### ISSUE TITLE
Incorrect lingering potion behavior with undead mobs

### ISSUE THREAD

**Issue by joserobjr** [GameModsBR/PowerNukkit#130]
### Expected Behavior

When undead mobs are affected by an area effect cloud of:
Instant health: Take damage
Instant damage: Regain health

### Actual Behavior

Instant health: Regain health, like a living entity
Instant damage: Take damage, like a living entity

### Steps to Reproduce

1. Spawn some zombies
2. Throw an instant health lingering potion on them
3. Wait the area effect wears out
4. Throw an instant damage lingering potion on them

### Debug information
Affects both `master` and `2.0/item/lingering-potion` branches

**Comment by HeyZeer0** [comment]
Fixed in #128

**Comment by joserobjr** [comment]
Reopened to remember me that I have to port to the `master` branch. I also moved the fix to #131
