### ISSUE TITLE
[2.0] List of blocks and PRs awaiting the waterlogging mechanic

### ISSUE THREAD

**Issue by joserobjr** [GameModsBR/PowerNukkit#151]
Waterlogging has not been implemented in Nukkit 2.0 yet and the blocks listed here are awaiting it to have it's properties adjusted.

- [x] #135 barrier
- [x] #160 kelp
- [x] #180 lectern

Waterlogging support will be added by #168 

~~Status: Awaiting #182 NukkitX#1164~~
Status: Ready to be implemented

**Comment by RORIdev** [comment]
#160 <
