### ISSUE TITLE
[1.X] Incorrect explosion behaviour with waterlogged blocks.

### ISSUE THREAD

**Issue by joserobjr** [GameModsBR/PowerNukkit#193]
Comparison on the links bellow (provided by @Gabriel8579). This issue will treat the 1.X behavior and #192 the 2.X version.

**Comment by Gabriel8579** [comment]
https://youtu.be/efLHclbVvV4 Comparing vanilla with 1.1.x (master branch)

**Comment by joserobjr** [comment]
2.X test result: https://github.com/GameModsBR/PowerNukkit/issues/192#issuecomment-585296309

I'm also going to try to fix it tonight. Thanks!

**Comment by joserobjr** [comment]
Related: NukkitX#1184
