### ISSUE TITLE
In 1.4.3 player can’t see others moving

### ISSUE THREAD

**Issue by w2333333** [GameModsBR/PowerNukkit#209]
1, In 1.4.3 player can’t see other is moving, they can see players stay in one point
2, I tried /tp player X Y Z to a place but it didn’t work

**Comment by pbs666** [comment]
yes,and i also find this bug in my server

**Comment by Htepple** [comment]
+1

**Comment by Htepple** [comment]
will it be fixed? :0

**Comment by Htepple** [comment]
this is a critical bug

**Comment by joserobjr** [comment]
Yes, it will be fixed @Htepple

**Comment by joserobjr** [comment]
Affects `v1.1.1.0-PN` and bellow.

The current dev branches `master` (currently at `1.2.0.0-PN-SNAPSHOT`) and `2.0-migration` (currently at `2.0.0.0-PN-SNAPSHOT`) aren't affected.

A hotfix version named `1.1.1.1-HOTFIX-PN` fill be released while `1.2.0.0-PN` milestone is not ready.

**Comment by joserobjr** [comment]
The hotfix has been released: https://github.com/GameModsBR/PowerNukkit/releases/tag/v1.1.1.1-HOTFIX-PN

Let me know if the bug persists or cause side-effects.
