### ISSUE TITLE
Bug with Nukkit Worlds

### ISSUE THREAD

**Issue by PocketMiner82** [GameModsBR/PowerNukkit#210]
I only want to know if it is possible to convert my old nukkit world (plotworld) to this nukkit, because there are UPDATE-blocks in my plotworld:
![2020-04-15_16h13_59](https://user-images.githubusercontent.com/44708000/79347583-2391b500-7f34-11ea-9fa3-d24bc036f8d2.png)

**Comment by joserobjr** [comment]
Can you give me more context?

Are the update blocks part of the world (intentionally placed) or from a conversion error from some software?

If it's intentional, it will still be displayed as update block. If it was a conversion error I really need more context, like what did you use to convert, if the screenshot was taken from a PowerNukkit server, 1.X or 2.X? etc.

**Comment by PocketMiner82** [comment]
The screenshot was taken from a PowerNukkit 1.X Server. I didn't convert the world (this is my CityBuild world) and the update blocks aren't there with the normal nukkit. If I right click the update blocks, they disappear. @joserobjr

**Comment by joserobjr** [comment]
Can you attach a MCA file containing the chunks with these blocks?

I only need one to investigate what's causing that block to be rendered.

You can send me privately if you prefer, my discord tag is `joserobjr#7357` and my e-mail is joserobjr@gamemods.com.br

**Comment by joserobjr** [comment]
You may use this tool to know which MCA file contains a given block/chunk position:
https://minecraft.tools/en/coordinate-calculator.php

**Comment by joserobjr** [comment]
A MCA file has been received by an other contributor and will be investigated.

**Comment by PocketMiner82** [comment]
> A MCA file has been received by an other contributor and will be investigated.

Ok, so I don't have to send mine?

**Comment by joserobjr** [comment]
> Ok, so I don't have to send mine?
You can send yours so I'll make sure it works too, I would use as an additional test data, but I can continue if you don't send.

Might be related to e7ae789bb6fa9b54292d1166bc0b7d8399d17c14

**Comment by joserobjr** [comment]
BTW, would be really nice if you share your MCA because your world have some random floating update blocks which the world that I have don't have, so I think that the fix that I'm working won't fix 100% of your world

**Comment by joserobjr** [comment]
@PocketMiner82 Can you try with this build?
https://github.com/GameModsBR/PowerNukkit/suites/648069967/artifacts/5517049

It was generated here: https://github.com/GameModsBR/PowerNukkit/runs/639239502
