### ISSUE TITLE
[1.2.0] If a crafting transaction fails, you can close the main player inventory (Action bar, exp bar, etc)

### ISSUE THREAD

**Issue by joserobjr** [GameModsBR/PowerNukkit#223]
### Expected Behavior

Never close the main player inventory, it's permanent.

### Actual Behavior

It closes the player inventory and the game mode UI overlays aren't displayed until you relog.

### Steps to Reproduce

1. Make a transaction fail somehow, I've used a known bug in the view below but I think that it can be induced with plugins
2. When the items vanishes from the inventory, wait a few seconds and hit Esc to close the inventory in the same time that the game would close. 
3. It's hard to time it right and requires some retries.
4. The inventory and your main UI will close when you succeed.

https://youtu.be/cDkFjOgU5Eo

### Debug information

* Debug link:
* Timings link (if relevant):
1.2.0.0-PN  Dev Build from 709e86edcddcf79a92cc3ac8c826c274d965326b

**Comment by joserobjr** [comment]
This is caused by a hack in `CraftingTransaction`
```java
ContainerClosePacket pk = new ContainerClosePacket();
pk.windowId = ContainerIds.NONE;
source.getServer().getScheduler().scheduleDelayedTask(new Task() {
    @Override
    public void onRun(int currentTick) {
        source.dataPacket(pk);
    }
}, 20);
```

**Comment by joserobjr** [comment]
1.3.0.0-PN makes it impossible to close permanent windows and the main player inventory is one of them.

**Comment by MrRazamataz** [comment]
I currently have a plugin that makes anvils work (for an older version of Nukkit) but do I still need that for the functionality of Anvils?

**Comment by joserobjr** [comment]
You don't, unless you have an other plugin which depends on it. PowerNukkit has builtin support to anvils.

**Comment by MrRazamataz** [comment]
Ok thanks.
