### ISSUE TITLE
Anvil: level cost calculated wrongly

### ISSUE THREAD

**Issue by AntonPPDS** [GameModsBR/PowerNukkit#226]
### Expected Behavior
Level is taken as much as is written on the anvil GUI

### Actual Behavior
Level is taken more than expected

### Steps to Reproduce
1. Take two of the enchanted books Sharpness III from creative.
2. Try to combine them in anvil. Expected cost of combining - 1L
3. You will see that 4L was taken instead of 1L

### Debug information
Version: https://github.com/GameModsBR/PowerNukkit/commit/0c7a9459d3358496795ac9508ac19059c96edd65

**Comment by joserobjr** [comment]
Related to #222

**Comment by AntonPPDS** [comment]
It's not. I've modified my build of the PowerNukkit so it does not takes level twice (removed handle of enchant event). It's another issue

**Comment by joserobjr** [comment]
It's not the same, but it's related, I know it's a different issue :)
