### ISSUE TITLE
Can't combine (Thorns2,Unbreaking3)+(Protection3,Unbreaking3) in anvil

### ISSUE THREAD

**Issue by joserobjr** [GameModsBR/PowerNukkit#239]
# 🐞 I found a bug

### ▶ Steps to Reproduce

| Input | Sacrifice 
|-------|----------
| ![image](https://user-images.githubusercontent.com/60366294/81396384-06fd2d00-912e-11ea-9056-70297ed3cbff.png) | ![image](https://user-images.githubusercontent.com/60366294/81396422-167c7600-912e-11ea-918d-28afd18435d3.png)

### ✔ Expected Behavior

![image](https://user-images.githubusercontent.com/60366294/81396477-25fbbf00-912e-11ea-8b62-4644fde0ecbb.png)

### ❌ Actual Behavior

You can't grab the result (the transaction is cancelled)

### 📋 Debug information

* **PowerNukkit version:** 1.2.0.2-PN-SNAPSHOT at fdb5fea
* **Debug link:** https://hastebin.com/ocatopujer

### 💬 Anything else we should know?

Reported by @AntonPPDS at https://github.com/GameModsBR/PowerNukkit/issues/222#issuecomment-625746508

**Comment by joserobjr** [comment]
## 🕷 Cause:
Java Edition preserves the enchantment insertion order but Bedrock Edition reorder them.

**Comment by joserobjr** [comment]
The order:
![image](https://user-images.githubusercontent.com/3679022/81489859-335d9a00-9251-11ea-8cbe-c2a707c967d9.png)

Missing:
fire_protection
frost_walker
mending
piercing
projectile_protection
protection
riptide
sharpness
silk_touch
smite

**Comment by joserobjr** [comment]
Oh no! Bedrock ordering are unreliable.

| Oh | No! |
|-|-|
| ![image](https://user-images.githubusercontent.com/3679022/81490143-d6fc7980-9254-11ea-94e1-efdf250faa2a.png) | ![image](https://user-images.githubusercontent.com/3679022/81490146-dd8af100-9254-11ea-834c-ec24c7f1a681.png)

I'm going to make the anvil logic ignore the order.

**Comment by AntonPPDS** [comment]
It seems the order of echantments is somehow related to the compatibility with item. I.e., if this is armor echantment on armor, it would be the most first, but I'm not sure.
