### ISSUE TITLE
Moving to PowerNukkit

### ISSUE THREAD

**Issue by RealTriassic** [GameModsBR/PowerNukkit#288]
# 🤷‍♀️ I have a question
How would i switch a Nukkit 1.0 Server to PowerNukkit? Would it be as easy as swapping the Nukkit 1.0 jar for the PowerNukkit jar?

**Comment by Jl1mbo** [comment]
Yes

**Comment by joserobjr** [comment]
Exactly, just make sure to backup your world because PowerNukkit 1.X saves the world a little differently and any chunk that uses the new blocks or contains waterlogged block might not revert well to NukkitX 1.X if you decide to stop using PowerNukkit.

`2.0`, when ready, might not have this issue
