### ISSUE TITLE
I think that PowerNukkit should have a Discord Server.

### ISSUE THREAD

**Issue by MrRazamataz** [GameModsBR/PowerNukkit#296]
I think that PowerNukkit should have a Discord Server as it would mean that people could discuss problems and assist other in getting them sorted. I know you can do that on GitHub but not all people can use GitHub well. Nukkit has a discord server and its quite useful the only problem is that they dont provide help for PowerNukkit.

**Comment by Htepple** [comment]
+1

**Comment by soturi1991** [comment]
+1

**Comment by Lusmft** [comment]
+1

**Comment by Jl1mbo** [comment]
+ 1

**Comment by Jl1mbo** [comment]
+1

**Comment by RORIdev** [comment]
It technically already has, although most part of its conversations are done in Portuguese.

**Comment by MrRazamataz** [comment]
Have you got a invite link?

**Comment by joserobjr** [comment]
It's not a PowerNukkit discord, it's bound to a Minecraft programming youtube channel and we talk about Minecraft development freely there (in Portuguese) and it happens to have a Nukkit section.

I think I might make a discord guild dedicated to PowerNukkit, which will be mainly in English but will have multi-language channels as needed.

I think it should have at least English, Portuguese and Chinese (even though we don't understand it, not even a single character lol, I see a lot of Chineses in the Bedrock community and the original Nukkit was made by Chineses as far as I know)

**Comment by joserobjr** [comment]
A discord guild is being configured

**Comment by joserobjr** [comment]
It's still being configured but the channels are already there. 

Here's the permanent invite: https://discord.gg/2jRdtsZ
