### ISSUE TITLE
Create a virtual PowerNukkit plugin so plugins can depend on it

### ISSUE THREAD

**Issue by joserobjr** [GameModsBR/PowerNukkit#314]
# ❇ Feature Request

If a plugin requires PowerNukkit right now, it needs to check the environment manually to see if it is running in PowerNukkit. With this change, the plugins will only need to set itself as dependent on the PowerNukkit plugin and the platform will do the dependency checks by itself, it would also help if a plugin needs to depend on specific PowerNukkit version and will prevent the plugin from loading on the raw NukkitX if it's not intended to run there.

**Comment by Jl1mbo** [comment]
Like NukkitX in pom.xml?

**Comment by joserobjr** [comment]
@Jl1mbo no, it would plugins to tell the system that it depends on PowerNukkit using the `plugin.yml`, like:
```yaml
depend: [PowerNukkit]
```

I just noticed that there's no way to tell the plugin version in this syntax, I might make it possible in future, something like:
```yaml
depend: [PowerNukkit:1.3+]
```
