### ISSUE TITLE
Bug enchanted item

### ISSUE THREAD

**Issue by Jl1mbo** [GameModsBR/PowerNukkit#318]
# 🐞 I found a bug
Bug enchanted item

### 📸 Screenshots / Videos

https://youtu.be/EfQg__42HKg

### ▶ Steps to Reproduce

Try enchant item

### ✔ Expected Behavior

The item was enchanted

### ❌ Actual Behavior

The subject was not enchanted

### 📋 Debug information

 *Latest build PN-115

**Comment by good777LUCKY** [comment]
https://github.com/NukkitX/Nukkit/pull/1525
Is this fix this issue?

**Comment by joserobjr** [comment]
Yes, he's fixing the enchanting table, it might be working in the next minor version.

**Comment by good777LUCKY** [comment]
> Yes, he's fixing the enchanting table, it might be working in the next minor version.
> 
> The version scheme is:
> `Upstream.Major.Minor.Patch`

It was merged but Sleepybear remove fix enchanting branch
