### ISSUE TITLE
Server time out (not mob plugin) {Latest release version/powernukkit-1.3.0.0-PN.jar}

### ISSUE THREAD

**Issue by MrRazamataz** [GameModsBR/PowerNukkit#319]
# 🐞 I found a bug
The server time out when a new player joins (Im pretty sure thats it).

### 📸 Screenshots / Videos
![server timeout](https://user-images.githubusercontent.com/56600481/86227521-065ca200-bb85-11ea-8dfc-7f03f04437d0.png)

### ▶ Steps to Reproduce
New player join server.

### ✔ Expected Behavior
Player to join fine.

### ❌ Actual Behavior
Server freezes and causes everyone to time out and get disconnected.

### 📋 Debug information
 https://hastebin.com/fawitamibo. Didnt capture timings,will try to.

* PowerNukkit version: powernukkit-1.3.0.0-PN.jar
* YouTrack: [PN-122](https://youtrack.gamemods.com.br/issue/PN-122)
* Debug link: https://hastebin.com/fawitamibo.
* Timings link (if relevant):  N/A

**Comment by MrRazamataz** [comment]
![timeout 2](https://user-images.githubusercontent.com/56600481/86229139-30af5f00-bb87-11ea-97e7-f722e9c6916d.png)
It happened again.
I might use the version found in actions.

**Comment by tuilakhanh** [comment]
I see the problem with welcomemessage plugin try remove it

**Comment by MrRazamataz** [comment]
Ok, it has always done that but I will remove it.

**Comment by MrRazamataz** [comment]
https://www.youtube.com/watch?v=Qe6A10G6htY&feature=youtu.be

**Comment by joserobjr** [comment]
I don't think the problem is with the welcome message plugin, I think it received an object that was in an invalid state and threw an exception when it tried to use it

**Comment by joserobjr** [comment]
Actually, I didn't interpret the stacktrace correctly, it hit an incompatible binary change to the `DataPacketReceiveEvent`, but I still don't think this should cause the server to hang completely. Hmm this is making me think... It's throwing an `Error`, not an `Exception`, so this could be bypassing a possible RakNet `catch(Exception)` which could be releasing the `ByteBuff` objects, if they are not released then the memory leaks and bad thing happens to the memory and CPU usage

**Comment by joserobjr** [comment]
If `RakNetSession.onClose()` fails, the `RakNetSession.deinitialize()` won't be called and won't release some reference counted objects:
https://github.com/NukkitX/Network/blob/ee440f7bd9b123d9aa98bb5658232621714ac0b0/raknet/src/main/java/com/nukkitx/network/raknet/RakNetSession.java#L635-L640

**Comment by joserobjr** [comment]
Some calls to `retain()` were removed, this could be causing the reported `IllegalReferenceCountException`

**Comment by joserobjr** [comment]
@MrRazamataz can you check if a build from 56be942 `#319 Downgrade RakNet to 1.6.17` (or above) fixed the issue?
https://github.com/GameModsBR/PowerNukkit/actions?query=branch%3Ableeding+

**Comment by MrRazamataz** [comment]
Is this a newer build?

**Comment by joserobjr** [comment]
Yes

**Comment by MrRazamataz** [comment]
Ok will do that.

**Comment by joserobjr** [comment]
Which version of the welcome message plugin are you using? Is it this one?
https://nukkitx.com/resources/welcome-messages.384/

**Comment by MrRazamataz** [comment]
I have removed it and updated to the version you said and all seems good. If that plugin a 2.0 plugin?

**Comment by joserobjr** [comment]
Yes, if you were using the plugin that I linked, it was logging errors because it is for Nukkit 2.X

**Comment by MrRazamataz** [comment]
Ok. The crash happend once more today. Would it be because I was looking in a events.txt log file whilst the server was on?

**Comment by joserobjr** [comment]
Did it happen again? The same way as reported?

**Comment by MrRazamataz** [comment]
It seems to be fine. Sometimes one player will time out but I think it's when their internet goes down or they leave Minecraft ithout clicking save and quit.

**Comment by MrRazamataz** [comment]
I downloaded the latest action snapshot and I just get stuck on loading resources...

**Comment by joserobjr** [comment]
Thank you for the info. I'm going to close as resolved.

The stuck on loading resources discussed at #345
