### ISSUE TITLE
Will PowerNukkit change something because of NukkitX to CloudBurst?

### ISSUE THREAD

**Issue by good777LUCKY** [GameModsBR/PowerNukkit#332]
# 🤷‍♀️ I have a question
NukkitX change project name to CloudBurst. Will PowerNukkit change something because of this?

**Comment by joserobjr** [comment]
Negative. The name won't change, however I was planning on moving PowerNukkit related repositories to it's own organization so we can group the related repositories better. When that happens I think GitHub will update all links and create redirections automatically. I got surprised by the name change
