### ISSUE TITLE
Hoppers make items disappear after being cooked. 

### ISSUE THREAD

**Issue by MrRazamataz** [GameModsBR/PowerNukkit#342]
# 🐞 I found a bug
When using a smoker or other cooker type and hoppers, the items disappear from the chest. 

### 📸 Screenshots / Videos

https://youtu.be/YJNfXArcqe0

### ▶ Steps to Reproduce

1. Place raw meat in top hopper
2. Wait for it to cook. 
3. Item disappears from final hopper. 

### ✔ Expected Behavior
Cooked item to appear in chests

### ❌ Actual Behavior
There is no cooked item. 

### 📋 Debug information
/About in video. 

### 💬 Anything else we should know?
It worked before I installed a newer build.

**Comment by MrRazamataz** [comment]
I believe this is fixed in the latest build, sorry about that.

**Comment by joserobjr** [comment]
No problem, thank you for sharing the issue.

I couldn't find which commit could have fixed the issue, so, if it happens again feel free to reopen with the updated output of the `/about` command
