### ISSUE TITLE
Stuck on loading resources.

### ISSUE THREAD

**Issue by MrRazamataz** [GameModsBR/PowerNukkit#345]
Something about this (https://github.com/GameModsBR/PowerNukkit/actions/runs/161520352) means that the client gets stuck on loading resources. The version before it is fine and the version after it is still affected. Basically means you can't go on the server.

**Comment by joserobjr** [comment]
That build is from an incomplete branch. Only use builds from the master/releases for stability or from the bleeding for preview/beta-test the next release. Other branches are dev-branches and are not ready.

**Comment by MrRazamataz** [comment]
Oh. Ok. 
Should I use this link (https://github.com/GameModsBR/PowerNukkit/actions?query=branch%3Ableeding) to get the complete branch?

**Comment by joserobjr** [comment]
Yes, that's the right link to get the safer snapshot builds.

Closing this issue because it got fixed at 331ff1c (however, the build has not been fully tested so odd bugs are expected)
