### ISSUE TITLE
Magic Block :D

### ISSUE THREAD

**Issue by Jl1mbo** [GameModsBR/PowerNukkit#355]
# 🐞 I found a bug

### 📸 Screenshots / Videos

https://youtu.be/BMCAcM4VAQk

### ▶ Steps to Reproduce

On video

### ✔ Expected Behavior

I do not know

### ❌ Actual Behavior

On video

### 📋 Debug information

* PowerNukkit version: ✍ last

**Comment by joserobjr** [comment]
Will be fixed when #356 gets merged.

**Comment by joserobjr** [comment]
Thank you for reporting :)
