### ISSUE TITLE
Arrows in offhand are black in the first person view

### ISSUE THREAD

**Issue by joserobjr** [GameModsBR/PowerNukkit#87]
It's normal in second and third person views
![image](https://user-images.githubusercontent.com/3679022/72583869-ab7d0a00-38c6-11ea-9eea-accc2dd73d80.png)

**Comment by PetteriM1** [comment]
You need to `.putByte(DATA_COLOR, 0)` to entity's data properties

**Comment by joserobjr** [comment]
Thank you! I'm going to try that tonight

**Comment by joserobjr** [comment]
Thank you! That really fixes it!
